### ISSUE TITLE
GlobalTimeout appears unused

### ISSUE THREAD

**Issue by grahamc** [tinkerbell/tink#198]
Right now, the global timeout is not actually used except at display-time in the `portal` project:

```
[grahamc@Petunia:~/projects/github.com/tinkerbell]$ rg GlobalTimeout
tink/executor/types.go
7:	GlobalTimeout int    `yaml:"global_timeout"`

tink/db/workflow.go
29:		GlobalTimeout int    `yaml:"global_timeout"`

portal/src/client/workflow.go
123:	wf.Timeout = strconv.Itoa(details.GlobalTimeout)

portal/src/pkg/types/workflow.go
26:	GlobalTimeout int    `yaml:"global_timeout"`
```

I propose the following semantics. Given a workflow:

```yaml
global_timeout: 30
tasks:
- name: "example"
  worker: "{{.device_1}}"
  actions:
  - name: "phase-1"
    image: hello-world
    timeout: 20
    command: sleep 20
  - name: "phase-2"
    image: hello-world
    timeout: 20
    command: sleep 20
```

1. phase-1 would execute to completion, take 20 seconds, and the entire workflow would have 10 seconds to complete the rest of the phases.
2. phase-2 would begin, run for 10 seconds, be killed, and the workflow is canceled.
