### ISSUE TITLE
tink fail to associate workflow with worker

### ISSUE THREAD

**Issue by wangxin311** [tinkerbell/tink#273]
We have experienced an issue on one of our BM host which is not able to execute any workflow after tink-worker container been started, this failure seems because of tink is not associate workflow with the hardware.

## Expected Behaviour
tink-server should associate workflow with hardware.

## Current Behaviour
Sometimes tink-server is failed to associate workflow with hardware and cause BM not able to run any of tink workflows

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
I am not sure how we landed into this issue, but I have cleaned up everything on the setup and just one hardware file and one workflow.

workflow 
```
/tmp # tink workflow list
+--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
| WORKFLOW ID                          | TEMPLATE ID                          | HARDWARE DEVICE                   | CREATED AT                    | UPDATED AT                    |
+--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
| 572c57e2-c22e-4689-a98c-6f37650505d9 | ae5525c2-baae-4450-82c3-3b8ab3f866b3 | {"device_1": "00:ae:cd:01:dd:18"} | 2020-08-28 20:02:44 +0000 UTC | 2020-08-28 20:02:44 +0000 UTC |
+--------------------------------------+--------------------------------------+-----------------------------------+-------------------------------+-------------------------------+
```
worker node IP and MAC:
```
/tmp # tink hardware all  | jq . | egrep "mac"
          "mac": "00:ae:cd:01:dd:18",

/tmp # tink hardware all  | jq . | egrep -A 3 "ip"
          "ip": {
            "address": "192.168.0.120",
            "family": 4,
```
tink workflow get
```
/tmp # tink workflow get 572c57e2-c22e-4689-a98c-6f37650505d9
version: '0.1'
name: linux_provisioning
global_timeout: 600
tasks:
- name: "os-installation"
  worker: "00:ae:cd:01:dd:18"
  volumes:
    - /dev:/dev
    - /dev/console:/dev/console
    - /lib/firmware:/lib/firmware:ro
  actions:
  - name: "disk-wipe"
    image: disk-wipe:v1
    timeout: 120
    environment:
      METADATA_HOST: 10.60.2.133
      IMAGE_HOST: 10.60.2.134
  - name: "disk-partition"
    image: disk-partition:v1
    timeout: 120
    environment:
      METADATA_HOST: 10.60.2.133
      IMAGE_HOST: 10.60.2.134
    volumes:
      - /statedir:/statedir
  - name: "install-root-fs"
    image: install-root-fs:v1
    timeout: 120
    environment:
      METADATA_HOST: 10.60.2.133
      IMAGE_HOST: 10.60.2.134
    volumes:
      - /statedir:/statedir
  - name: "install-grub"
    image: install-grub:v1
    timeout: 120
    environment:
      METADATA_HOST: 10.60.2.133
      IMAGE_HOST: 10.60.2.134
    volumes:
      - /statedir:/statedir
  - name: "cloud-init"
    image: cloud-init:v1
    timeout: 120
    environment:
      METADATA_HOST: 10.60.2.133
      IMAGE_HOST: 10.60.2.134
    volumes:
      - /statedir:/statedir
  - name: "post-install"
    image: post-install:v1
    timeout: 120
    environment:
      METADATA_HOST: 10.60.2.133
      IMAGE_HOST: 10.60.2.134
    volumes:
      - /statedir:/statedir
  - name: "reboot"
    image: reboot:v1
    timeout: 120
    environment:
      METADATA_HOST: 10.60.2.133
      IMAGE_HOST: 10.60.2.134
    volumes:
      - /statedir:/statedir
```

1. logs from tink in non-working scenario.
```
2020-08-28T20:17:12.549Z	INFO	grpc-server/workflow.go:232	done getting a workflow	{"service": "github.com/tinkerbell/tink", "workflowID": "572c57e2-c22e-4689-a98c-6f37650505d9", "currentWorker": "", "currentTask": "", "currentAction": "", "currentActionIndex": "0", "currentActionState": "ACTION_PENDING", "totalNumberOfActions": 7}
```
2. logs from tink in working scenario.
```
2020-08-28T20:27:35.560Z	INFO	grpc-server/workflow.go:232	done getting a workflow	{"service": "github.com/tinkerbell/tink", "workflowID": "86ab7a66-bf83-467d-8c7a-9eb694a984ab", "currentWorker": "fde7c87c-d154-447e-9fce-7eb7bdec90c0", "currentTask": "os-installation", "currentAction": "disk-wipe", "currentActionIndex": "0", "currentActionState": "ACTION_IN_PROGRESS", "totalNumberOfActions": 7}
```
From above logs, looks like tink is not associate the new created workflow  "572c57e2-c22e-4689-a98c-6f37650505d9" with any of "currentWorker".
