### ISSUE TITLE
are multiple tasks in a template supported?

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/tink#479]
Are multiple tasks in a template supported?

```yaml
version: "0.1"
name: multiple_workers
global_timeout: 180
tasks:
  - name: "os-installation"
    worker: "{{.device_1}}"
    environment:
      MIRROR_HOST: 192.168.2.1
    actions:
      - name: "action number 1"
        image: alpine:latest
        command:
          - "/bin/sleep"
          - "5"
        timeout: 90
      - name: "action 2"
        image: alpine:latest
        command:
          - "/bin/sleep"
          - "5"
        timeout: 30
        environment:
          MIRROR_HOST: 192.168.1.214
  - name: "finalizer"
    worker: "{{.device_2}}"
    environment:
      MIRROR_HOST: 192.168.2.1
    actions:
      - name: "finalizer action 1"
        image: alpine:latest
        command:
          - "/bin/sleep"
          - "5"
        timeout: 90
      - name: "finalizer action 2"
        image: alpine:latest
        command:
          - "/bin/sleep"
          - "5"
        timeout: 30
        environment:
          MIRROR_HOST: 192.168.1.214
```

when I create a workflow using this template the second task does not get executed. From what I can tell in the code (tink-server and tink-worker), this is not supported. Is that accurate?
